// src/constants/responseMessages.ts
export const RESPONSES = {
  SUCCESS: {
    ADMIN_GROUP_LISTED: 'Groups listed successfully.',
    SYSTEM_MODULE_LISTED: 'System Modules listed successfully.',
    PAGE_LISTED: 'Pages listed successfully.',
    ADMIN_GROUP_CREATED: 'Groups created successfully.',
    ADMIN_GROUP_UPDATED: 'Groups updated successfully.',
    ADMIN_GROUP_DETAILS: 'Groups detail fetched successfully.',
    PAGE_DETAILS: 'Page detail fetched successfully.',
    PAGE_DELETED: 'Page deleted successfully.',
    ADMIN_GROUP_DELETED: 'Group deleted successfully.',
    PAGE_CREATED: 'Page created successfully.',
    PAGE_UPDATED: 'Page updated successfully.',
    PASSWORD_RESET: 'Password has been reset successfully!',
    LOGIN: 'Login successfully!',
    FORGOT_PASSWORD_EMAIL_SENT: 'We have sent you an email with password reset link.',
    ADMIN_CREATED: 'Admin created and sending password on email successfully.',
    ADMIN_USER_DETAIL_FETCHED_SUCCESS: 'Admin detail fetched successfully.',
    ADMIN_USER_DETAIL_UPDATE_SUCCESS: 'Admin detail updated successfully.',
    USER_DETAIL_UPDATE_SUCCESS: 'User detail updated successfully.',
    GET_PROFILE: 'Profile details fetched successfully.',
    ADMIN_STATUS_CHANGE: 'Admin status changed successfully.',
    ADMIN_DELETE_SUCCESS: 'Admin deleted successfully.',
    ADMIN_LIST_FETCHED_SUCCESS: 'Admin list fetched successfully.',
    STATUS_UPDATED: 'Status updated successfully.',
    MEDIA_LISTED: 'Media listed successfully.',
    MEDIA_CREATED: 'Media added successfully.',
    MEDIA_DELETED: 'Media Deleted successfully.',
    SLOT_CONFIG_CREATED: 'Slot configuration created successfully.',
    SLOT_CONFIG_FETCHED: 'Slot configuration fetched successfully.',
    SLOT_IMAGES_FETCHED: 'Slot images fetched successfully.',
    SPIN_RESULT_CREATED: 'Spin result created successfully.',
    SPIN_RESULT_FETCHED: 'Spin result fetched successfully.',
    USER_LOGGS_DELETED: 'User Logss Deleted Successfully',
    USER_LOGGS_FETCHED: 'User Logss Fetched Successfully',
    USER_LOGGS_NOT_FOUND: 'User Loggs Not Found',
    OTP_SENT: 'OTP sent successfully',
    OTP_VERIFIED: 'OTP verified successfully',
    SLOT_INFO_FETCHED: 'Slot Info fetched successfully',
    GAME_CONFIG_SET_SUCCESS: 'Game configuration set successfully.',
    GAME_CONFIG_FETCHED_SUCCESS: 'Game configuration fetched successfully.',
    SCORE_CALCULATION_SUCCESS: 'Score calculated successfully.',
    REWARD_FETCHED_SUCCESS: 'Reward fetched successfully.',
    USER_ELIGIBLE_TO_PLAY: 'User is eligible to play.',
    USER_LOGS_FETCHED_SUCCESS: 'User logs fetched successfully.',
    USER_LOG_DELETED_SUCCESS: 'User log deleted successfully.',
    DAILY_LIMIT_EXCEEDED: 'Daily play limit is over.',
    OTP_SENT_SUCCESSFULLY: 'OTP sent successfully.',
    OTP_VERIFICATION_SUCCESS: 'OTP verified successfully.',
    STORE_CREATED: 'Store created successfully.',
    STORE_LISTED: 'Stores listed successfully.',
    STORE_STATUS_UPDATED: 'Store status updated successfully.',
    STORE_DETAILS_UPDATED: 'Store details updated successfully.',
    STORE_DETAILS: 'Store details fetched successfully.',
    STORE_DELETED: 'Store deleted successfully.',
    TEMPLATES_LISTED: 'Templates list fetched successfully.',
    TEMPLATE_CONFIG: 'Template configed successfully.',
    TEMPLATE_CONFIG_UPDATED: 'Template updated successfully.',
    TEMPLATE_CONFIG_CREATED: 'Template created successfully.',
    OTP_ALREADY_SENT: 'OTP already sended in this mobile number, Please wait before requesting a new one.',
    CUSTOMER_BLOCKED: 'Customer blocked of a given numbers.',
    CUSTOMER_LIST: 'These are all customers.',
    CUSTOMER_DELETED: 'Customer log deleted successfully.',
    BLOCKED_NUMBER_LISTED: 'Blocked customer are listed.',
    CUSTOMER_LOG_EXPORTED: 'Customer log exported successfully.',
    ALL_CUSTOMER_DELETED: 'All customers logs deleted successfully.',
    ALL_STORE_DELETED: 'All stores deleted successfully.',
    REWARDS_RESET: 'Rewards reset successfully.',
    STORE_LIST: 'Store listed successfully',
    COINFLIP_UPDATED: 'Game configuration updated successfully.',
    COINFLIP_CREATED:'Game configuration created successfully.',
    USER_LISTING_FETCHED_SUCCESS:'User logs fetch successfully.',
    USER_DELETE_SUCCESS:'User deleted successfully',
    EXPORT_SUCCESS: 'Logs exported successfully.',
  },
  ERROR: {
    GENERIC: 'Something went wrong.',
    TOKEN_EXPIRED: 'Your link is expired please try again.',
    NO_TOKEN_PROVIDED: 'No token provided!',
    INVALID_TOKEN: 'Token is invalid!',
    UNAUTHORIZED: 'Unauthorized!',
    USER_NOT_FOUND: 'User not found.',
    ADMIN_GROUP_NOT_FOUND: 'Group is Invalid.',
    USER_INACTIVE: 'Your accoount is deactivated. Please contact admin.',
    INVALID_CREDENTIALS: 'Invalid credentials.',
    EMAIL_ALREADY_EXIST: 'Email already exists.',
    ADMIN_FAILED_TO_CREATE: 'Admin failed to create.',
    EMAIL_SEND_FAILED: 'Email sending failed.',
    TRANSACTION_FAILED: 'Something wrong sending email.',
    ADMIN_USER_NOT_FOUND: 'Admin not found.',
    ADMIN_USER_DETAIL_UPDATE_FAILED: 'Admin detail failed to update.',
    USER_DETAIL_UPDATE_FAILED: 'User detail failed to update.',
    ADMIN_STATUS_NOT_CHANGE: 'Admin status failed to change.',
    ADMIN_DELETE_FAILED: 'Admin failed to delete.',
    PAGE_ALREADY_EXISTS: 'Page already exists.',
    NO_SUCH_FILE: 'no such file or directory.',
    IMAGE_REQUIRED: 'Images are required.',
    ADMIN_GROUP_HAS_USERS: 'Group cannot be deleted as it is assigned to users.',
    SLOT_CONFIG_NOT_FOUND: 'Slot configuration not found.',
    INVALID_SECTION_COUNT: 'Number of images must match section count.',
    INVALID_PRIZE_DISTRIBUTION: 'Invalid prize distribution configuration.',
    INVALID_SPECIAL_CONDITIONS: 'Invalid special conditions configuration.',
    SLOT_IMAGES_NOT_FETCHED: 'Slot images not fetched',
    MEDIA_DIR_NOT_EXISTS: 'Media directory does not exist',
    SPIN_RESULT_NOT_CREATED: 'Error in creating spin result',
    DAILY_LIMIT_COMPLETED: 'Daily Limit complted , come back after some time',
    USER_LOGGS_DELETE_FAIL: 'User Logg Deletion Failed',
    USER_LOGGS_NOT_FOUND: 'User Loggs Not Found',
    OTP_SEND_FAILED: 'Failed to send OTP',
    OTP_VERIFICATION_FAILED: 'Failed to verify OTP',
    INVALID_OTP: 'Invalid OTP provided',
    DAILY_LIMIT_REACHED: 'Daily play limit reached',
    SLOT_INFO_NOT_FETCHED: 'Failed to fetch slot info',
    GAME_CONFIG_NOT_FOUND: 'Game configuration not found.',
    INVALID_GAME_STATE: 'Invalid game data submitted.',
    INVALID_SCORE: 'Invalid score calculation.',
    USER_LOG_CREATION_FAILED: 'User log creation failed.',
    USER_LOG_NOT_FOUND: 'User log not found.',
    FAILED_TO_SEND_OTP: 'Failed to send OTP.',
    ALREADY_EXIST: 'User name already exists.',
    INVALID_INPUT: 'mobile number is incorrect.',
    NO_LOGIN: 'User is not allowed to logged in.',
    NO_STORE_NAME: 'Store name is invalid.',
    NO_OTP: 'otp is invalid.',
    STORE_NOT_FOUND: 'Store not found.',
    SELECTED_TEMPLATE_NOT_FOUND: 'Selected Template not found.',
    INVALID: 'Please enter a valid phone number and your name',
    INVALID_REQUEST: 'Mobile number, OTP, and Name are required.',
    TEMPLATE_NOT_FOUND: 'No default template found.',
    NO_PRIZE_AVAILABLE: 'No prize available for selection.',
    INVALID_MOBILE: 'Mobile numbers must be a comma-separated string.',
    CUSTOMER_NOT_FOUND: 'customer not found.',
    BLOCKED_USER: 'User for this number is blocked.',
    ALREADY_PLAYED_IN_LAST_HOUR: 'You already played in last 24 hours.',
    NO_CUSTOMER_FOUND: 'Not found any customer yet.',
    INVALID_ID: 'Please enter a valid id.',
    USER_NAME_EXISTS: 'User name already exists.',
    MOBILE_NUMBER_EXISTS: 'Mobile number already exists.',
    MISSING_PARAMETERS: 'Store ID and Template ID are required.',
    INVALID_DATA: 'stripe_texts must be an array.',
    INVALID_MOBILE_NUMBER: 'You entered an invalid mobile number.',
    NO_CUSTOMER_LOGS: 'No customer logs are found.',
    EXPORT_FAILED: 'Exporting customer logs failed.',
    TOKEN_REQUIRED: 'Authorization token is required.',
    USER_BLOCKED: 'You are not allowed to play.',
    ALREADY_PLAYED: 'You have already played within the last 24 hours.',
    INVALID_REQUEST_SENT: 'Mobile number and Name are required.',
    ERROR_GENERATING_LOGS: 'Error generating customer logs.',
    ERROR_SENDING_SMS: 'Failed to send OTP. Please try again later.',
    INVALID_ID_LENGTH: 'Invalid or empty array of IDs.',
    INCORRECT_OTP: 'Incorrect OTP entered.',
    NOT_DEFAULT_STORE: 'Login not allowed. This store is not marked as default.',
    STORE_OWNER_NOT_ALLOWED: 'You are not allowed to play.',
    NO_RECORDS_FOUND: 'No records found.',
    RECORDS_DELETION_FAILED: 'Failed to delete records.',
  },
} as const;

export type ResponseMessageKey = keyof typeof RESPONSES.SUCCESS | keyof typeof RESPONSES.ERROR;
