//src/constant/urls.js
export const loginUrl = 'admin/auth/signin'
export const forgotpasswordUrl = 'admin/auth/forgot-password'
export const adminGroupListUrl = 'admin/admin-group/list'
export const adminGroupDelete = 'admin/admin-group'
export const resetPasswordUrl = 'admin/auth/reset-password'
export const adminGroupStatusUpdate = 'admin/admin-group'
export const adminProfileUrl = 'admin/profile'
export const createAdmin = 'admin/admin/create'
export const viewAdmin = 'admin/admin/view/'
export const updateAdmin = 'admin/admin/update/'
export const getSystemModulesList = 'admin/system-modules'
export const getMediaList = 'admin/media'
export const deleteMedia = 'admin/media'
export const createcmspage = 'admin/page'
export const adminGroupAddUrl = 'admin/admin-group'
export const adminGroupDetailsUrl = 'admin/admin-group'
export const adminGroupUpdateUrl = 'admin/admin-group'
export const deleteAdmin = 'admin/admin/delete/'
export const changeAdminStatus = 'admin/admin/change-status/'
export const adminGroupDataList = 'admin/admin-group'
export const adminDataList = 'admin/admin/listing'
export const admincreatecmspage = 'admin/page'
export const admingetcmspage = 'admin/page/index'
export const admincmspagestatuschange = 'admin/page'
export const deletecmspage = 'admin/page'
export const getcmsbyid = 'admin/page'
export const editcmspage = 'admin/page'

export const setSlotMachinegameconfig = 'admin/games/slot-machine/config'
export const getSlotMachinegameconfigcontent = 'admin/games/slot-machine/config'
export const deleteSlotMachineuserloggs = 'admin/games/slot-machine/user-logs'
export const getSlotMachineuserloggs = 'admin/games/slot-machine/user-logs'
export const deleteAllSlotMachineuserloggs = 'admin/games/slot-machine/user-logs/delete'
export const exportSlotMachineuserloggs = 'admin/games/slot-machine/user-logs/export'

export const setMemoryGameConfig = 'admin/games/memory-game/config'
export const getMemoryGameConfig = 'admin/games/memory-game/config'
export const getMemoryGameuserlogs = 'admin/games/memory-game/user-logs'
export const deleteMemoryGameUserLog = 'admin/games/memory-game/user-logs'
export const deleteAllMemoryGameUserLogs = 'admin/games/memory-game/user-logs/delete'
export const exportMemoryGameUserLogs = 'admin/games/memory-game/user-logs/export'

export const getSpinTemplatedata = 'admin/games/spin'
export const getSpinConfig = 'admin/games/spin'
export const exportCustomerLogs = 'admin/games/spin/customer-logs/export'
export const customerLogs = 'admin/games/spin/customer-logs'
export const deleteCustomerLogs = 'admin/games/spin/customer-logs/'
export const deleteAllCustomerLogs = 'admin/games/spin/customer-logs/delete'
export const Spinconfig = 'admin/games/spin'

export const setPlinkoGameConfig = 'admin/games/plinko/config'
export const getPlinkoGameConfig = 'admin/games/plinko/config'
export const getPlinkoGameuserlogs = 'admin/games/plinko/user-logs'
export const deletePlinkoGameUserLog = 'admin/games/plinko/user-logs'
export const deleteAllPlinkoGameUserLogs = 'admin/games/plinko/user-logs/delete'
export const exportPlinkoGameUserLogs = 'admin/games/plinko/user-logs/export'

export const setCoinFlipGameConfig = 'admin/games/coin-flip/config'
export const getCoinFlipGameConfig = 'admin/games/coin-flip/config'
export const getCoinFlipuserlogs = 'admin/games/coin-flip/user-logs'
export const deleteCoinFlipGameUserLogs = 'admin/games/coin-flip/user-logs'
export const deleteAllCoinFlipGameUserLogs = 'admin/games/coin-flip/user-logs/delete'
export const exportCoinFlipGameUserLogs = 'admin/games/coin-flip/user-logs/export'
